[package]
name = "headlines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.3" }
serde = "1.0.136"
iced_native = "0.4.0"
tracing = "0.1.30"
tracing-subscriber = "0.3.7"
